"""
Execution Agent: 构建工程
通过 ToolDispatcher 调用工具，确保可审计、可隔离
"""
from runtime.agents.base_agent import BaseAgent
from typing import Dict, Any, List
from runtime.tools.tool_dispatcher import ToolDispatcher

class ExecutionAgent(BaseAgent):
    def __init__(self):
        super().__init__("Execution")
        self.tool_dispatcher = ToolDispatcher()
        self.tool_executions: List[Dict[str, Any]] = []
    
    async def execute(self, context: Dict[str, Any], task_id: str) -> Dict[str, Any]:
        """
        职责：工程执行器：生成配置、构建索引、运行评测、产出交付物
        通过 ToolDispatcher 调用工具，确保可审计、可隔离
        """
        self.tool_executions = []
        artifacts = {
            "config_generated": False,
            "index_built": False,
            "evaluation_run": False
        }
        
        # 1. 生成配置文件（通过工具）
        config_result = await self.tool_dispatcher.execute(
            "file_write",
            {
                "path": f"artifacts/rag_project/{task_id}/config.yaml",
                "content": self._generate_config(context)
            },
            task_id
        )
        self.tool_executions.append(config_result)
        if config_result.success:
            artifacts["config_generated"] = True
        
        # 2. 如果配置生成成功，继续构建索引（示例）
        if artifacts["config_generated"]:
            # 这里可以调用更多工具
            # 例如：构建向量索引、运行数据预处理等
            pass
        
        return {
            "decision": "execution_complete",
            "reason": "工程执行完成",
            "artifacts": artifacts,
            "tool_executions": [t.to_dict() if hasattr(t, 'to_dict') else t for t in self.tool_executions] if hasattr(self, 'tool_executions') and self.tool_executions else [],
            "state_update": {
                "execution_agent_executed": True,
                "artifacts": artifacts
            }
        }
    
    def _generate_config(self, context: Dict[str, Any]) -> str:
        """生成配置文件内容"""
        spec = context.get("spec", {})
        return f"""# RAG System Configuration
# Generated by Agentic AI Delivery OS

project_name: {spec.get('project_name', 'rag_project')}
data_sources: {spec.get('data_sources', [])}
embedding_model: {spec.get('embedding_model', 'default')}
vector_store: {spec.get('vector_store', 'faiss')}

# Generated at: {context.get('created_at', 'unknown')}
"""
    
    def get_governing_question(self) -> str:
        return "如何将意图实现为可运行软件？"

